ipset fix

diff --git a/block-countries b/block-countries
--- a/block-countries
+++ b/block-countries
@@ -9,22 +9,22 @@ function DIE () {
 	}
 trap DIE EXIT
 
-chain=block.countries
+chain=blockcountries
 rulecheck="`iptables -vnL`"
 
 
 # Check that a set exists in bash:
-ipset -L block.countries  >/dev/null 2>&1
+ipset -L blockcountries  >/dev/null 2>&1
 if [ $? -ne 0 ]; then
-		ipset create $chain hash:net 
+		ipset create blockcountries hash:net 
 fi
 
 
-if [[ ! '*--match-set  block.countries*' == rulecheck ]]; then 
-  echo " block.countries rule found"
+if [[ ! '*match-set blockcountries*' == rulecheck ]]; then 
+  echo " blockcountries rule found"
 else
-  echo " block.countries rule not found"
-	iptables -A INPUT -p tcp -m set --match-set block.countries src -m multiport --dport 22,80,443 -j DROP
+  echo " blockcountries rule not found"
+	iptables -A INPUT -p tcp -m set --match-set blockcountries src -m multiport --dport 22,80,443 -j DROP
 
 fi
 
@@ -60,12 +60,12 @@ echo optimizing reduced $zn to $znn: $(( 100 - ( $znn * 100 / $zn ) ))% savings	
 echo '*raw'
 for ip in $(cat zones.$$ )
 do
-	ipset -exist add $chain $ip
+	ipset -exist add blockcountries $ip
 	echo -A $chain -s $ip -j DROP
 	# echo -A $chain -j DROP -s $ip -p tcp --dport 22
 done
 echo COMMIT
-) | iptables-restore -n
+) #| iptables-restore -n
 
 
 #if [ $(iptables -t raw -nL PREROUTING | grep -c $chain ) -lt 3 ]
